site_name: Serverless ハンズオン
theme: "material"
extra_css:
  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
  - "css/custom.css"
extra:
  font:
    text: "Noto Sans JP"
    code: "Consolas"
markdown_extensions:
  - fontawesome_markdown
  - admonition
site_dir: ../docs
nav:
  - 環境構築:
      setup/cloud9.md